//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MeteoIT2.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Stations
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Stations()
        {
            this.StationUsers1 = new HashSet<StationUsers>();
        }

        public int Id { get; set; }
        [Display(Name = "نام ایستگاه")]
        public string StationName { get; set; }
        [Display(Name = "نام لاتین ایستگاه")]
        public string LatinStationName { get; set; }
        [Display(Name = "کد WMO")]
        public string WMOCode { get; set; }
        [Display(Name = "کد ICAO")]
        public string ICAOCode { get; set; }
        [Display(Name = "نوع ایستگاه")]
        public Nullable<int> IdStationTypes { get; set; }
        [Display(Name = "نوع جمع آوری داده")]
        public Nullable<int> IdDataCollectionTypes { get; set; }
        [Display(Name = "بستر مخابراتی")]
        public Nullable<int> IdNetworkTypes { get; set; }
        [Display(Name = "مسئول ایستگاه")]
        public Nullable<int> IdStationUsers { get; set; }
        [Display(Name = "نوع جمع آوری داده")]
        public virtual DataCollectionTypes DataCollectionTypes { get; set; }
        [Display(Name = "بستر مخابراتی")]
        public virtual NetworkTypes NetworkTypes { get; set; }
        [Display(Name = "نوع ایستگاه")]
        public virtual StationTypes StationTypes { get; set; }
        [Display(Name = "مسئول ایستگاه")]
        public virtual StationUsers StationUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<StationUsers> StationUsers1 { get; set; }
    }
}
